/* Centralized UI copy for the Incident Report workflow. Keeping every
   user-facing label/message in one object (rather than inline JSX strings)
   is what makes future translation possible without touching component
   logic. Field labels that must match the reference document's printed
   wording live in incidentModel.js instead (they are content, not UI
   chrome, and PDF layout code reads them directly). */
export const incidentCopy = {
  workflowTitle: 'Incident Report',
  draftBadge: 'Draft',
  readyBadge: 'Ready',
  completedBadge: 'Completed',
  autosaveSaving: 'Saving…',
  autosaveSaved: 'Saved',
  autosaveError: 'Save failed \u2014 try Save Now',
  autosaveIdle: '',
  saveNow: 'Save Now',
  confirmDiscardDraft: 'Discard the current incident draft? This cannot be undone.',
  confirmReplaceDraft: 'Starting a new incident report will replace the current draft. Continue?',
  confirmClearSignature: 'Remove this signature?',
  confirmRemoveWitness: 'Remove this witness and their statement?',
  confirmRemoveTeamMember: 'Remove this investigation team member?',
  nav: {
    back: 'Back',
    next: 'Next',
    finish: 'Go to Review',
  },
  yesNo: {
    unselected: 'Not answered',
    yes: 'Yes',
    no: 'No',
  },
  details: {
    title: 'Incident Details',
    intro: 'Basic facts about where and when this happened.',
    workplaceLocation: 'Workplace location',
    incidentDate: 'Date of incident',
    incidentTime: 'Time of incident',
    writtenReportDateTime: 'Date/time of written report',
    reportedToSupervisorDateTime: 'Date/time incident reported to supervisor',
    investigatorSectionTitle: 'Reporting Supervisor / Investigator',
    investigatorName: 'Name',
    investigatorTitle: 'Title / position',
    investigatorPhone: 'Contact number',
    investigatorEmail: 'Email address',
    incidentSpecificLocation: 'Where the incident occurred (specify)',
    detailedIncidentDescription: 'Detailed description of the incident',
  },
  injury: {
    title: 'Injury',
    intro: 'Was anyone injured?',
    injuryOccurred: 'Was anyone injured?',
    injuredPartySectionTitle: 'Injured Party',
    injuredPartyName: 'Name, title, years in company & current trade',
    injuredPartyPhone: 'Contact info (phone)',
    injuredPartyEmail: 'Contact info (email)',
    natureOfInjury: 'Nature of injury (select all that apply)',
    natureOfInjuryOther: 'Other (specify)',
    bodyPartsAffectedText: 'Body part(s) affected',
    treatmentLevel: 'Treatment',
    treatmentFirstAid: 'First aid',
    treatmentBeyondFirstAid: 'Services beyond first aid',
    treatingPhysicianOrClinic: 'Name & address of treating physician/clinic',
    injuryRemarks: 'Remarks/comments',
    bodyDiagramTitle: 'Part of body affected (mark all areas that apply)',
    bodyDiagramHelp: 'Tap or click on the diagram to mark an affected area. Tap a mark again to remove it.',
    undoMark: 'Undo last mark',
    clearMarks: 'Clear all marks',
  },
  witnesses: {
    title: 'Witnesses',
    intro: 'Add up to 3 witnesses. Witnesses are optional.',
    addWitness: 'Add witness',
    removeWitness: 'Remove witness',
    name: 'Name',
    company: 'Company',
    supervisor: 'Supervisor',
    phone: 'Contact phone',
    email: 'Contact email',
    statement: 'Statement',
    signature: 'Signature',
    signatureDate: 'Date',
    empty: 'No witnesses added yet.',
    maxReached: 'Maximum of 3 witnesses reached.',
  },
  property: {
    title: 'Property Damage',
    intro: 'Was any property or equipment damaged?',
    propertyDamageOccurred: 'Was there property damage?',
    propertyOrMaterialDamaged: 'List property/material damaged',
    natureOfDamage: 'Nature of damage',
    objectMachineToolOrSubstance: 'Object(s)/machine(s)/tool(s)/substance(s) inflicting damage',
    approximateDamageCost: 'Approximate cost of damage',
  },
  cause: {
    title: 'Cause Analysis',
    intro: 'Select every cause that applies, then mark the single best primary, root cause if possible.',
    primaryHint: 'Primary, root cause',
    setPrimary: 'Set as primary cause',
    primaryBadge: 'Primary',
    otherLabel: 'Other (specify)',
    noneSelected: 'No causes selected yet.',
  },
  notes: {
    title: 'Notes & Investigation Team',
    supervisorNotes: 'Superintendent/supervisor notes & summary (immediate actions taken & how to help prevent recurrence)',
    safetyConsultantNotes: 'Safety consultant notes & summary',
    teamSectionTitle: 'Investigation Team',
    addMember: 'Add team member',
    removeMember: 'Remove member',
    memberName: 'Name',
    memberTitle: 'Title',
    memberSignature: 'Signature',
    memberDate: 'Date',
    empty: 'No investigation team members added yet.',
    maxReached: 'Maximum of 4 team members reached.',
  },
  review: {
    title: 'Review & Export',
    readinessTitle: 'Before you export',
    markReady: 'Mark Ready',
    markReadyHint: 'All required fields are complete. Mark Ready to generate a final PDF without the DRAFT watermark.',
    readyHeadline: 'This report is marked ready \u2014 generate the final PDF below.',
    completedHeadline: 'This report is complete. The final PDF has been generated.',
    draftHeadline: 'This report is still in progress.',
    draftExplain: 'You can export a draft copy at any time -- it will be watermarked "DRAFT" until it is marked ready.',
    editedAfterReady: 'This report was edited after being marked ready, so it has returned to draft. Mark Ready again to generate a final PDF.',
    generatePdf: 'Generate PDF',
    generating: 'Generating PDF…',
    regeneratePdf: 'Regenerate PDF',
    download: 'Download PDF',
    print: 'Print',
    share: 'Share',
    stale: 'The report has changed since this PDF was generated. Regenerate to include the latest changes.',
    pagesGenerated: 'pages generated',
    startNew: 'Start New Incident Report',
  },
  home: {
    startButton: 'Start Incident Report',
    continueButton: 'Continue Incident Report',
    availableBadge: 'Available',
  },
};
